import {createSlice} from '@reduxjs/toolkit';
import {DollarSate} from '@interfaces/reduxInterface';

const SLICE_NAME = 'DOLLARS';

// Initial state for Redux store:
const initialState: DollarSate = {
  dollars: [],
};

// Create Redux state slice
const dollarsSlice = createSlice({
  name: SLICE_NAME,
  initialState,
  reducers: {
    // Define reducers
    setDollars: (state, action) => {
      state.dollars = action.payload;
    },
    displayDollar: (state, action) => {
      const objIndex = state.dollars.findIndex(dollar => dollar.nombre === action.payload);
      if (state.dollars.filter(dollar => dollar.show).length > 1) {
        state.dollars[objIndex].show = !state.dollars[objIndex].show;
      } else {
        state.dollars[objIndex].show = true;
      }
    },
  },
});

// Export actions generated by 'createSlice()':
export const {setDollars, displayDollar} = dollarsSlice.actions;

// Export reducer generated by 'createSlice()':
export default dollarsSlice.reducer;
