import { createSlice } from '@reduxjs/toolkit'
import { DolarSate } from '@interfaces/reduxInterface';

const SLICE_NAME = 'DOLARS';

// Initial state for Redux store:
const initialState: DolarSate = {
  dolars: [],
}

// Create Redux state slice
const dolarsSlice = createSlice({
  name: SLICE_NAME,
  initialState,
  reducers: {
    // Define reducers
    setDolars: (state, action) => {
      state.dolars = action.payload;
    },
    displayDolar: (state, action) => {
      const objIndex = state.dolars.findIndex((dolar => dolar.nombre == action.payload));
      if (state.dolars.filter(dolar => dolar.show).length > 1) {
        state.dolars[objIndex].show = !state.dolars[objIndex].show;
      } else {
        state.dolars[objIndex].show = true;
      }
    }
  },
});

// Export actions generated by "createSlice()":
export const { setDolars, displayDolar } = dolarsSlice.actions

// Export reducer generated by "createSlice()":
export default dolarsSlice.reducer
